# Generated by Django 4.0.5 on 2022-08-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'priority',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rep_date', models.DateField(blank=True, null=True)),
                ('vchr_title', models.CharField(max_length=50)),
                ('vchr_remarks', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('fk_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.client')),
                ('fk_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.priority')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_detail',
            },
        ),
        migrations.CreateModel(
            name='Task_Detail',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_remarks', models.CharField(max_length=1000)),
                ('date_action', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('fk_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.task')),
                ('fk_user_detail', models.ForeignKey(blank=True, db_column='fk_user_detail', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.userdetail')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='fk_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.type'),
        ),
        migrations.AddField(
            model_name='task',
            name='fk_user_detail',
            field=models.ForeignKey(blank=True, db_column='fk_user_detail', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.userdetail'),
        ),
    ]
